import {
  Languages,
  BookOpen,
  Brain,
  Code,
  FlaskConical,
  Dna,
  Atom,
  Calculator,
  Globe,
  Landmark,
  Scale,
  Briefcase,
  Palette,
  Music,
  Heart,
  Cpu,
  Database,
  BarChart3,
  Rocket,
  Leaf,
  Microscope,
  Book,
  Theater,
  Gamepad2,
  Clock,
} from "lucide-react"

export const iconMap = {
  language: Languages,
  "book-open": BookOpen,
  brain: Brain,
  code: Code,
  flask: FlaskConical,
  dna: Dna,
  atom: Atom,
  calculator: Calculator,
  globe: Globe,
  landmark: Landmark,
  scale: Scale,
  briefcase: Briefcase,
  palette: Palette,
  music: Music,
  heart: Heart,
  cpu: Cpu,
  database: Database,
  chart: BarChart3,
  rocket: Rocket,
  leaf: Leaf,
  microscope: Microscope,
  book: Book,
  theater: Theater,
  gamepad: Gamepad2,
  clock: Clock,
} as const
